name: node

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - run: npm run test:lint
    - run: npm run build
    - run: npm run test:unit
    - run: npm run cov:send
